databases:
  - name: w-manual-bot-db
    plan: free
    databaseName: w_manual_bot
    user: w_manual_bot_user

services:
  - type: web
    name: w-manual-bot
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --config gunicorn_config.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: w-manual-bot-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: USE_LITE_AI_SERVICE
        value: true