# Generated by Django 5.0.4 on 2025-03-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='block',
            field=models.BooleanField(default=False, verbose_name='ブロック'),
        ),
    ]
